# Site settings
title: Confidence in Coding
header-img: img/home-bg.png
email: andrew.ramell@gmail.com
copyright_name: ramell86
description: > # this means to ignore newlines until "baseurl:"
  My Trials and Tribulations Learning to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ramell86
github_username:  ramell86
learn_profile: ramell86
email_username: andrew.ramell@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
